// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: logic/api.proto

package logic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KickOffLineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 昵称
}

func (x *KickOffLineReq) Reset() {
	*x = KickOffLineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickOffLineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOffLineReq) ProtoMessage() {}

func (x *KickOffLineReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOffLineReq.ProtoReflect.Descriptor instead.
func (*KickOffLineReq) Descriptor() ([]byte, []int) {
	return file_logic_api_proto_rawDescGZIP(), []int{0}
}

func (x *KickOffLineReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type KickOffLineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *KickOffLineResp) Reset() {
	*x = KickOffLineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickOffLineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOffLineResp) ProtoMessage() {}

func (x *KickOffLineResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOffLineResp.ProtoReflect.Descriptor instead.
func (*KickOffLineResp) Descriptor() ([]byte, []int) {
	return file_logic_api_proto_rawDescGZIP(), []int{1}
}

func (x *KickOffLineResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *KickOffLineResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_logic_api_proto protoreflect.FileDescriptor

var file_logic_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x22, 0x29, 0x0a, 0x0e, 0x4b, 0x69, 0x63, 0x6b,
	0x4f, 0x66, 0x66, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x4c, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x43, 0x0a, 0x03,
	0x41, 0x70, 0x69, 0x12, 0x3c, 0x0a, 0x0b, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x4f,
	0x66, 0x66, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logic_api_proto_rawDescOnce sync.Once
	file_logic_api_proto_rawDescData = file_logic_api_proto_rawDesc
)

func file_logic_api_proto_rawDescGZIP() []byte {
	file_logic_api_proto_rawDescOnce.Do(func() {
		file_logic_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_logic_api_proto_rawDescData)
	})
	return file_logic_api_proto_rawDescData
}

var file_logic_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logic_api_proto_goTypes = []interface{}{
	(*KickOffLineReq)(nil),  // 0: logic.KickOffLineReq
	(*KickOffLineResp)(nil), // 1: logic.KickOffLineResp
}
var file_logic_api_proto_depIdxs = []int32{
	0, // 0: logic.Api.KickOffLine:input_type -> logic.KickOffLineReq
	1, // 1: logic.Api.KickOffLine:output_type -> logic.KickOffLineResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logic_api_proto_init() }
func file_logic_api_proto_init() {
	if File_logic_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logic_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickOffLineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickOffLineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logic_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logic_api_proto_goTypes,
		DependencyIndexes: file_logic_api_proto_depIdxs,
		MessageInfos:      file_logic_api_proto_msgTypes,
	}.Build()
	File_logic_api_proto = out.File
	file_logic_api_proto_rawDesc = nil
	file_logic_api_proto_goTypes = nil
	file_logic_api_proto_depIdxs = nil
}
