name: api
work-id: 1
port: 10001
log: "./configs/api.yaml"
etcd:
  endpoints: ["lark-etcd:12379"]
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
mysql:
  address: localhost:3306
  username: root
  password: root
  db: game
  max_open_conn: 20
  max_idle_conn: 10
  conn_lifetime: 120000
  charset: utf8
redis:
  address: ["172.21.219.70:6379"]
  db: 0
  password: root
  prefix: "LK:"

