name: api
work-id: 1
port: 10001
log: "./configs/api.yaml"
ws_server: # 时间单位为（毫秒）
  server_id:
  name: lark_ws_server
  port: 7301 # 为grpc端口+1
  write_wait: 10000
  pong_wait: 600000
  ping_period: 540000
  max_message_size: 4096
  read_buffer_size: 4096
  write_buffer_size: 4096
  header_length: 4
  chan_client_send_message: 100
  chan_server_read_message: 1000
  chan_server_register: 1000
  chan_server_unregister: 1000
  max_connections: 20000
  minimum_time_interval: -1
  log:
grpc_server:
  name: gateway
  server_id: 1
  port: 19999
  max_connection_idle: 0
  max_connection_age: 0
  max_connection_age_grace: 0
  time: 7200000
  timeout: 20000
  connection_limit: 2000
  streams_limit: 2000
  max_recv_msg_size: 4096
  credential:
    cert_file: ./configs/tls/grpc/server.pem
    key_file: ./configs/tls/grpc/server.key
  jaeger:
    host_port: "lark-jaeger:6831"
    sampler_type: "const"
    param: 1
    log_spans: true
    buffer_flush_interval: 1
    max_packet_size: 0
logic_server:
  name: logic
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: logic
match_server:
  name: match
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: match
battle_server:
  name: battle
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: battle
etcd:
  endpoints: ["172.21.219.70:20000","172.21.219.70:20002","172.21.219.70:20004"]
  schema: game
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
mysql:
  address: 172.21.219.70:3306
  username: root
  password: root
  db: game
  max_open_conn: 20
  max_idle_conn: 10
  conn_lifetime: 120000
  charset: utf8
redis:
  address: ["172.21.219.70:6379"]
  db: 0
  password: root
  prefix: "LK:"
jaeger:
  host_port: "172.21.219.70:6831"
  sampler_type: "const"
  param: 1
  log_spans: true
  buffer_flush_interval: 1
  max_packet_size: 0
  enabled: false

