name: lark_test
log: "./configs/logger.yaml"
grpc_server:
  name: lark_test
  server_id: 1
  port: 19999
  max_connection_idle: 0
  max_connection_age: 0
  max_connection_age_grace: 0
  time: 7200000
  timeout: 20000
  connection_limit: 2000
  streams_limit: 2000
  max_recv_msg_size: 4096
  credential:
    cert_file: ./configs/tls/grpc/server.pem
    key_file: ./configs/tls/grpc/server.key
  jaeger:
    host_port: "lark-jaeger:6831"
    sampler_type: "const"
    param: 1
    log_spans: true
    buffer_flush_interval: 1
    max_packet_size: 0
push_online_server:
  name: lark_online_push_server
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: lark.com
chat_member_server:
  name: lark_chat_member_server
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: lark.com
etcd:
  endpoints: ["lark-etcd:12379"]
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
mysql:
  address: "lark-mysql-user:13306"
  username: root
  password: lark2022
  db: lark_user
  max_open_conn: 20
  max_idle_conn: 10
  conn_lifetime: 120000
  charset: utf8
mongo:
  address: "lark-mongo-msg:27017"
  username: admin
  password: lark2022
  db: lark
  direct: false
  timeout: 5000
  max_pool_size: 20
  retain_chat_records: 3650
redis:
  address: ["lark-redis:63791"]
  db: 0
  password: lark2022
  prefix: "LK:"
platforms:
 - type: 1
   name: Android
   offline_push: true
 - type: 2
   name: iOS
   offline_push: true
msg_consumer:
  address: ["lark-kafka:9092"]
  topic: ["msg2inbox"]
  group_id: push
elasticsearch:
  address: ["http://localhost:9200"]
  username: elastic
  password: lart2022
  ca_cert: ./configs/tls/elasticsearch/ca.crt